### ISSUE TITLE
Agar.io menu appears to viewer connected to repeater.js

### ISSUE THREAD

**Issue by ItsNickBarry** [pulviscriptor/agario-devtools#3]
When a viewer and streamer are connected to repeater.js, and the viewer is following a bot, the Agar.io menu sometimes appears when the bot is eaten.  The respawned bot's actions are still visible behind the menu.  The menu remains until the bot is eaten and respawns again.

I can't predict when this bug occurs, and don't know how to repeat it. I am using Firefox 38.

**Comment by pulviscriptor** [comment]
I know this bug. I just click "spawn" and menu disappears.
Theoretically I can try to fix it, but this tools made for developing and this bug doesn't make any troubles.
If you do want me to fix it, tell me.

**Comment by ItsNickBarry** [comment]
I was intending to use the repeater as the primary means of viewing my bot's activities.  Do you know of a better tool for this purpose?  If not, it would be nice to have this fixed.

**Comment by pulviscriptor** [comment]
To solve this bug I need add timeout (which unstable solution) or/and parse protocol (check my answer in #4).
Please, just press "spawn" to hide menu when you debugging your client. Any input from viewer will be ignored, so it will not break anything.
Thank you.
