### ISSUE TITLE
Incorrect viewer field of view on streamer reconnect to repeater

### ISSUE THREAD

**Issue by ItsNickBarry** [pulviscriptor/agario-devtools#4]
If the streamer disconnects and connects again, or is replaced by a new streamer, the viewer does not see the correct part of the map.

**Comment by pulviscriptor** [comment]
Hi.
I will try to explain the problem.
What you want - is some client, that will parse protocol and remember balls/FOV position/other information. Then when you connect to it there will be server emulator that will "compile" packets with initial packets, data about area size, FOV position and balls list.
So when protocol changes your client and server emulator will break, so you will need something that works with raw data and does not parse protocol to debug it. And that is what agario-devtools currently is.
You see what I mean?
It's like client inside tools which were made for debugging the client. So when protocol changes, everything crashing.

You can try [agario-webclient](https://github.com/GeoffreyFrogeye/agario-webclient) and test your bot inside browser and see what he is doing.
And if something will break, you can debug it on raw data with agario-devtools. First connect viewer, then streamer. When you want repeat - you disconnect streamer, reconnect viewer, and connect streamer. That what I meant in readme.

**Comment by ItsNickBarry** [comment]
Thank you for clarifying.  I will look into the agario-webclient you mentioned.
